language: node_js

node_js:
  - stable

stages:
  - test
  - release

jobs:
  include:
    - stage: test
      before_script: npm run lint
      script: npm run cover
      after_success: npm run coveralls
    - stage: release
      if: tag IS present
      deploy:
        provider: npm
        email: "$NPM_EMAIL"
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
